package com.nexio.excercices;

import com.nexio.excercices.model.Product;
import com.nexio.excercices.persistence.ProductRepository;
import com.nexio.excercices.utils.Utils;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.ApplicationArguments;
import org.springframework.boot.ApplicationRunner;
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.context.support.AbstractApplicationContext;
import org.springframework.core.env.Environment;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RestController;

import javax.annotation.PostConstruct;
import java.util.Arrays;
import java.util.logging.Logger;

@SpringBootApplication
public class Excercice1Application implements ApplicationRunner {

    private static final Logger LOG
            = Logger.getLogger(Excercice1Application.class.getName());

    private static final Integer DEFAULT_AMOUNT_OF_AUTOGENERATED_PRODUCTS = 10;

    @Autowired
    private AbstractApplicationContext appContext;

    @Autowired
    private Environment env;

    @Autowired
    private ProductRepository productRepository;

    public static void main(String[] args) {
        LOG.info("L'appli pour l'excercice 1 a démarré!");
        SpringApplication.run(Excercice1Application.class, args);
        LOG.info("L'appli pour l'excercice 1 s'est actif!");
    }

    @GetMapping("/")
    public String homePage() {
        return "Bienvenue à mon API";
    }

    @PostConstruct
    public void initApplication() throws RuntimeException {
        // Grace à  on peut fermer l'application avec AbstractApplicationContext#doClose
        appContext.registerShutdownHook();
    }

    private void generateSampleProducts(Integer amountOfProductsToGenerate) {
        for (int i = 0; i < amountOfProductsToGenerate; i++) {
            final Product product = Utils.generateProduct(i % 2 == 0);
            final Product savedProduct = productRepository.save(product);
            LOG.info(String.format("Le produit \"%s\" a été ajouté avec succès", savedProduct));
        }
    }

    @Override
    public void run(ApplicationArguments args) throws Exception {
        if (args.containsOption("number-of-products")) {
            Integer numberOfProducts = Integer.parseInt(
                    args.getOptionValues("number-of-products").get(0)
            );

            generateSampleProducts(numberOfProducts);
        }
    }
}

